---
- name: Update RHEL Servers
  hosts: all
  become: true
  roles:
    - role: server_update
      tags:
        - server_update
    - role: snapshot_cleanup
      tags:
        - snapshot_cleanup
    - role: cluster_update
      tags:
        - cluster_update
    - role: satellite_register
      tags:
        - satellite_register
    - role: satellite_upload
      tags:
        - satellite_upload

- name: Restore Server from the Snapshot
  hosts: localhost
  gather_facts: false
  roles:
    - role: server_restore
      tags:
        - server_restore
    - role: satellite_content_view
      tags: 
        - satellite_content_view
    - role: content_view_version_cleanup
      tags: 
        - satellite_content_cleanup
    - role: content_view_errata
      tags: 
        - content_view_errata
