---
- name: Update RHEL Servers
  hosts: all
  become: true
  roles:
    - role: aws_instance_info
      tags: aws_instance_info
    - role: cluster_node_stop
      tags: cluster_node_stop
    - role: cluster_node_operations
      tags: cluster_node_operations
    - role: cluster_node_start
      tags: cluster_node_start
    - role: aws_tag_management
      tags: aws_tag_management
    - role: aws_tag_create
      tags: aws_tag_create
    - role: satellite_tag_create
      tags: satellite_tag_create
    - role: aws_tag_delete
      tags: aws_tag_delete
    - role: server_snapshot
      tags: server_snapshot
    - role: aws_server_recovery
      tags: aws_server_recovery
    - role: server_update
      tags:
        - server_update
    - role: snapshot_cleanup
      tags:
        - snapshot_cleanup
    - role: cluster_unstandby_node
      tags:
        - cluster_unstandby_node
    - role: cluster_standby_node
      tags:
        - cluster_standby_node
    - role: cluster_backup
      tags:
        - cluster_backup
    - role: cluster_verify
      tags:
        - cluster_verify
    - role: cluster_update
      tags:
        - cluster_update
    - role: satellite_register
      tags:
        - satellite_register
    - role: server_restore
      tags:
        - server_restore

- name: Restore Server from the Snapshot
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - role: satellite_cv_operations
      tags: satellite_cv_operations
    - role: satellite_check
      tags: satellite_check
    - role: satellite_content_view
      tags: satellite_content_view
    - role: content_view_version_cleanup
      tags: satellite_content_cleanup
    - role: content_view_errata
      tags: content_view_errata
    - role: satellite_upload
      tags: satellite_upload
    - role: aws_role_assume
      tags: aws_role_assume

