---
# tasks file for content_view_errata
- name: "Include errata by date"
  theforeman.foreman.content_view_filter_rule:
    username: "{{ satellite_deployment_admin_username }}"
    password: "{{ satellite_deployment_admin_password }}"
    server_url: "{{ satellite_deployment_server }}"
    content_view: "{{ satellite_content_view }}"
    organization: "{{ satellite_deployment_organization }}"
    validate_certs: false
    content_view_filter: "{{ errata_filter_name }}"
    state: present
    date_type: updated
    types:
      - bugfix
      - security
    end_date: "{{ errata_end_date }}"
