---
- name: AWS Instance Snapshot
  block:
    - name: Retrieve Attached Volume ID(s)
      amazon.aws.ec2_instance_info:
        instance_ids: "{{ instance_id }}"
        region: "{{ aws_region | default('ap-southeast-2') }}"
        access_key: "{{ assumed_role.sts_creds.access_key }}"
        secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        session_token: "{{ assumed_role.sts_creds.session_token }}"
      register: instance_info
      delegate_to: localhost
    
    - name: Create Snapshot of the Attached Volumes
      amazon.aws.ec2_snapshot:
        volume_id: "{{ item }}"
        description: "Snapshot for volume {{ item }} of instance {{ instance_id }}"
        region: "{{ aws_region }}"
        access_key: "{{ assumed_role.sts_creds.access_key }}"
        secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        session_token: "{{ assumed_role.sts_creds.session_token }}"
      loop: "{{ instance_info.instances[0].block_device_mappings | map(attribute='ebs.volume_id') | list }}"
      delegate_to: localhost
      register: snapshot_results
