---
- name: Assume Role
  amazon.aws.sts_assume_role:
    role_arn: "arn:aws:iam::{{ aws_account_no }}:role/{{ aws_role }}"
    role_session_name: "assumeRoleSession"
    region: "{{ aws_region }}"
  register: assumed_role
  delegate_to: localhost

- name: Retrieve Instance ID from Metadata
  ansible.builtin.uri:
    url: http://169.254.169.254/latest/meta-data/instance-id
    return_content: true
  register: instance_metadata

- name: Set Instance ID as Fact
  ansible.builtin.set_fact:
    instance_id: "{{ instance_metadata.content }}"

- name: Retrieve Attached Volume ID(s)
  amazon.aws.ec2_instance_info:
    instance_ids: "{{ instance_id }}"
    region: "{{ aws_region }}"
    access_key: "{{ assumed_role.sts_creds.access_key }}"
    secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    session_token: "{{ assumed_role.sts_creds.session_token }}"
  register: instance_info
  delegate_to: localhost

- name: Create Snapshot of the Attached Volumes
  amazon.aws.ec2_snapshot:
    volume_id: "{{ item }}"
    description: "Snapshot for volume {{ item }} of instance {{ instance_id }}"
    region: "{{ aws_region }}"
    access_key: "{{ assumed_role.sts_creds.access_key }}"
    secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    session_token: "{{ assumed_role.sts_creds.session_token }}"
  loop: "{{ instance_info.instances[0].block_device_mappings | map(attribute='ebs.volume_id') | list }}"
  delegate_to: localhost
  register: snapshot_results

- name: Verify Snapshot Creation
  ansible.builtin.debug:
    msg: "Snapshot created successfully: {{ snapshot_results.results | map(attribute='snapshot_id') | list }}"

