---
- name: Check the Cluster Status
  block:
    - name: Gather service facts
      ansible.builtin.service_facts:
    
    - name: Verify if Cluster Services are Running
      ansible.builtin.assert:
        that:
          - ansible_facts.services[item + '.service'].state == 'running'
        fail_msg: "{{ item }} service is not running!"
        success_msg: "{{ item }} service is running."
      loop: "{{ ha_system_services_list }}"
      loop_control:
        label: "{{ item }}"
    
    - name: Verify the status of the cluster nodes
      ansible.builtin.command: crm_node -l
      register: cluster_node_status
      run_once: true
    
    - name: Extract node status
      ansible.builtin.set_fact:
        lost_nodes: "{{ cluster_node_status.stdout_lines | select('search', 'lost') | list }}"
    
    - name: Fail if any node is lost
      ansible.builtin.assert:
        that:
          - lost_nodes | length == 0
        fail_msg: "Some nodes are in 'lost' state"
        success_msg: "All nodes are in a healthy 'member' state."
    
    - name: Verify Status of the fencing resource
      ansible.builtin.command: pcs resource status "{{ fence_resource_name }}"
      register: fence_rs_status
    
    - name: Fail if Fence Resource failed
      ansible.builtin.assert:
        that:
          - "'Started' in fence_rs_status.stdout"
        fail_msg: "Fencing resource failed"
        success_msg: "Fencing resource Started. Proceeding to other checks"
    
    - name: Verify Status of the HANA resources
      ansible.builtin.command: pcs resource status "{{ hana_pcs_resource }}"
      register: hana_rs_status
    
    - name: Extract Master node from PCS status
      ansible.builtin.set_fact:
        master_node: "{{ hana_rs_status.stdout | regex_search('Masters: \\[ ([^\\]]+)\\]', '\\1') | first }}"
      when: "'Masters' in hana_rs_status.stdout"
    
    - name: Fail if HANA Resource failed
      ansible.builtin.assert:
        that:
          - "'Masters' in hana_rs_status.stdout"
        fail_msg: "HANA resource failed or stopped {{ hana_rs_status.stdout_lines }}"
        success_msg: "HANA resource Promoted on {{ master_node | default(omit) }}"

  rescue:
    - name: Log failure of cluster health check
      ansible.builtin.lineinfile:
        path: /var/log/cluster_health.log
        line: "Cluster health check failed at {{ ansible_date_time.iso8601 }}. Reason: {{ ansible_failed_result.msg | default('Unknown error') }}"
        create: yes

  always:
    - name: Log execution status
      ansible.builtin.lineinfile:
        path: /var/log/cluster_health.log
        line: "Cluster health check completed with status: {{ 'Success' if ansible_failed_result is not defined else 'Failure' }}."
        create: yes
