---
one_week_ago: "{{ lookup('pipe', 'date -u --date=\"1 week ago\" +%Y-%m-%dT%H:%M:%SZ') }}"
aws_region: "ap-southeast-2"
system_services_list:
  - sshd
  - rsyslog
  - pcsd
  - pacemaker
  - corosync
satellite_deployment_organization: 'RedHat'
satellite_deployment_admin_username: 'admin'
satellite_deployment_admin_password: password
satellite_lifecycle: [Build, NonProd, PreProd, Prod]
satellite_content_view: test
satellite_deployment_server: "https://rhsatellite.example.org"
satellite_kat_cert: "katello-ca-consumer-latest.noarch.rpm"
sat_activation_key: "ak-rhel8-nonprod"
yum_repo_dir: "/etc/yum.repos.d"
satellite_content_view_version_cleanup_keep: 2
errata_filter_name: "filter-security-bugfix"
errata_end_date: "2025-02-05"

# Variables for satellite_upload role
satellite_product: "AWS"
satellite_repository: "aws-cloudwatch-repo"
package_url: "https://amazoncloudwatch-agent.s3.amazonaws.com/amazon_linux/amd64/latest/{{ package_name }}"
package_tmp: "/tmp"
package_name: "amazon-cloudwatch-agent.rpm"
#Variables for cluster_update role
fence_resource_name: "fence_resource"
hana_pcs_resource: "sap_hana-clone"
ha_system_services_list:
      - pcsd
      - pacemaker
      - corosync
system_services_list:
      - pacemaker
      - corosync
# Variables for cluster_backup role
cluster_backup_dir: '/tmp'
# Variables for server_restore role
instance_id: "i-06f2ae9866ae9448b"  # Replace with your instance ID

# Variables for AWS Roles
aws_role: 
aws_account_no: 

# Variables for the Tags
tag_value: "Summary To Add to the Tag's value Something"
tag_key_value: "Server_Name_Update"
