---
one_week_ago: "{{ lookup('pipe', 'date -u --date=\"1 week ago\" +%Y-%m-%dT%H:%M:%SZ') }}"
aws_region: "ap-southeast-2"
update_system_services_list:
  - sshd
  - rsyslog
  - pcsd
  - pacemaker
  - corosync
satellite_deployment_organization: 'RedHat'
satellite_deployment_admin_username: 'admin'
satellite_deployment_admin_password: redhat123
#satellite_lifecycle: [NonProd, PreProd, Prod]
satellite_lifecycle: [NonProd, PreProd]
#satellite_content_view: CV-Comp
satellite_content_views: [CV-AWS,CV-Calyptia,CV-Microsoft,CV-Comp]
satellite_sap_content_view: CV-RHEL8
satellite_deployment_server: "https://rhsatellite.example.org"
satellite_kat_cert: "katello-ca-consumer-latest.noarch.rpm"
#satellite_base_url: "rhsatpool1.prod.cba"
sat_activation_key: "ak-rhel8-nonprod"
yum_repo_dir: "/etc/yum.repos.d"
satellite_content_view_version_cleanup_keep: 0
sat_errata_filter_name: "filter-security-bugfix"
sat_errata_end_date: "2025-02-05"

# Variables for satellite_upload role
sat_package_tmp: "/tmp"
sat_dictionary:
      products:
        - name: AWS
          repositories:
            - name: aws-cloudwatch-repo
              package_name: amazon-cloudwatch-agent.rpm
              package_url: "https://amazoncloudwatch-agent.s3.amazonaws.com/redhat/amd64/latest"
            - name: aws-ssm
              package_name: amazon-ssm-agent.rpm
              package_url: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64"
            - name: aws-cli
              package_name: awscli-exe-linux-x86_64.zip
              package_url: "https://awscli.amazonaws.com"
#        - name: Tanium
#          repositories:
#            - name: tanium-rhel8-repo
#              package_name: tanium.rpm
#              package_url: "https://artifactory.com/"
# 	- name: Flexera
#          repositories:
#            - name: fnms-rhel8-repo
#              package_name: fnms.rpm
#              package_url: "https://artifactory.com/"
#	- name: Splunk
#          repositories:
#            - name: splunk-rhel8-repo
#              package_name: splunk.rpm
#              package_url: "https://artifactory.com/"

#satellite_product: "AWS"
#satellite_repository: "aws-cloudwatch-repo"
#package_url: "https://amazoncloudwatch-agent.s3.amazonaws.com/amazon_linux/amd64/latest/{{ package_name }}"
#package_name: "amazon-cloudwatch-agent.rpm"
#Variables for cluster_update role
fence_resource_name: "fence_resource"
hana_pcs_resource: "sap_hana-clone"
ha_system_services_list:
      - pcsd
      - pacemaker
      - corosync
system_services_list:
      - pacemaker
      - corosync
srv_check_system_services_list:
      - pacemaker
      - corosync
      - sshd
# Variables for cluster_backup role
cluster_backup_dir: '/tmp'
# Variables for server_restore role
instance_id: "i-06f2ae9866ae9448b"  # Replace with your instance ID

# Variables for AWS Roles
aws_role: AcoeCICDRole
aws_account_no: 273354650151

# Variables for the Tags
aws_tag_key_value: "Server_Name_Update"
aws_tag_value: 
aws_tag_key_cleanup: Server_update_
aws_snapshot_id: 

# Instance Info
metadata_paths: 
  - "instance-id"
  - "local-ipv4"
  - "public-ipv4"
  - "ami-id"
  - "placement/availability-zone"
