---
- name: "Find content view versions of {{ cv.name }}"
  redhat.satellite.resource_info:
    server_url: "{{ satellite_deployment_server | default(omit) }}"
    username: "{{ satellite_deployment_admin_username | default(omit) }}"
    password: "{{ satellite_deployment_admin_password | default(omit) }}"
    validate_certs: false
    organization: "{{ satellite_deployment_organization }}"
    resource: content_view_versions
    params:
      content_view_id: "{{ cv.id }}"
  register: versions

- name: "Delete unused content view versions of {{ cv.name }}"
  ansible.builtin.include_tasks: delete_cv_versions.yml
  vars:
    cv_name: "{{ cv.name }}"
    cv_versions: "{{ (versions.resources | rejectattr('environments') | rejectattr('composite_content_view_ids') |
                   rejectattr('published_in_composite_content_view_ids') | map(attribute='version') | map('float') | sort |
                   map('string') | reverse | list )[satellite_content_view_version_cleanup_keep:] }}"
