---
- name: Include role variables
  ansible.builtin.include_vars: "vars/all.yml"

- name: "Verify if the host has been already registered to the Satellite"
  theforeman.foreman.host_info:
    username: "{{ satellite_deployment_admin_username }}"
    password: "{{ satellite_deployment_admin_password }}"
    server_url: "{{ satellite_deployment_server }}"
    organization: "{{ satellite_deployment_organization }}"
    name: "{{ inventory_hostname }}"
    validate_certs: false
  register: sat_host_reg
  when: not server_unregister | bool
  delegate_to: localhost

- name: Find files in the directory
  ansible.builtin.find:
    paths: "{{ yum_repo_dir }}"
    file_type: file
  register: found_files
  when: 
    - sat_host_reg.host is none
    - not server_unregister | bool

- name: Debug the files found (optional)
  ansible.builtin.debug:
    var: found_files.files
  when: 
    - sat_host_reg.host is none
    - not server_unregister | bool

- name: Remove files if any are found
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ found_files.files }}"
  when:
    - sat_host_reg.host is none
    - not server_unregister | bool

- name: Ensure that subscription_manager is used to manage subscriptions
  ansible.builtin.command: "subscription-manager config --rhsm.manage_repos=1"
  when:
    - sat_host_reg.host is none
    - not server_unregister | bool

- name: Install Katello CA from Capsule with SSL verify off
  ansible.builtin.dnf:
    name: "{{ satellite_deployment_server }}/pub/{{ satellite_kat_cert }}"
    state: present
    sslverify: false
    validate_certs: false
    rhsm_baseurl: "{{ satellite_base_url | default(omit)}}"
    disable_gpg_check: true
  register: katello_ca_install
  when: not server_unregister | bool

- name: Debug - Katello CA install result
  ansible.builtin.debug:
    var: katello_ca_install
  when: not server_unregister | bool

- name: Register system to Satellite using activation key
  community.general.redhat_subscription:
    state: present
    org_id: "{{ satellite_deployment_organization }}"
    activationkey: "{{ sat_activation_key }}"
    force_register: true
  register: subman_reg
  when: not server_unregister | bool

- name: Debug - registration result
  ansible.builtin.debug:
    var: subman_reg
  when: not server_unregister | bool

- name: "Show a host"
  theforeman.foreman.host_info:
    username: "{{ satellite_deployment_admin_username }}"
    password: "{{ satellite_deployment_admin_password }}"
    server_url: "{{ satellite_deployment_server }}"
    organization: "{{ satellite_deployment_organization }}"
    name: "{{ inventory_hostname }}"
    validate_certs: false
  register: sat_host_reg
  when: not server_unregister | bool

- name: Check if sat_host_reg.host is set
  ansible.builtin.assert:
    that:
      - sat_host_reg.host is not none
    fail_msg: "Host is null; the registration did not succeed."
    success_msg: "Host is set; registration succeeded."
  when: not server_unregister | bool

- name: Debug - registration result
  ansible.builtin.debug:
    var: sat_host_reg
  when: not server_unregister | bool

- name: Download Test package
  ansible.builtin.dnf: 
    name: tree    
    download_only: true
  register: dnf_download_test
  when: not server_unregister | bool  

- name: Check The tasks
  ansible.builtin.debug:
    var: dnf_download_test
  when: not server_unregister | bool
  
- name: Assert The Server Can Download the package
  ansible.builtin.assert:
    that: dnf_download_test is defined
  fail_msg: "Server cannot download the package"
  success_msg: "Server can Download The Package. Registration Successful"
  when: not server_unregister | bool

- name: "Check if host is registered in Satellite"
  theforeman.foreman.host_info:
    username: "{{ satellite_deployment_admin_username }}"
    password: "{{ satellite_deployment_admin_password }}"
    server_url: "{{ satellite_deployment_server }}"
    organization: "{{ satellite_deployment_organization }}"
    name: "{{ inventory_hostname }}"
    validate_certs: false
  register: sat_host_reg
  failed_when: false      # Don't fail if the host doesn't exist
  changed_when: false     # This is just an info check
  when: server_unregister | bool
  delegate_to: localhost

- name: "Set fact indicating if Satellite knows about this host"
  ansible.builtin.set_fact:
    is_in_satellite: "{{ sat_host_reg.host is defined }}"
  when: server_unregister | bool
  delegate_to: localhost

- name: "Delete host from Satellite if present"
  theforeman.foreman.host:
    username: "{{ satellite_deployment_admin_username }}"
    password: "{{ satellite_deployment_admin_password }}"
    server_url: "{{ satellite_deployment_server }}"
    organization: "{{ satellite_deployment_organization }}"
    name: "{{ inventory_hostname }}"
    state: absent
    validate_certs: false
  when:
    - server_unregister | bool
    - is_in_satellite
  delegate_to: localhost

- name: "Unregister the local system from Satellite subscription"
  community.general.redhat_subscription:
    state: absent
  when: server_unregister | bool

- name: "Unregister the local system from Satellite subscription"
  ansible.builtin.shell: subscription-manager clean
  when: server_unregister | bool

- name: "Re-check host in Satellite (should not exist)"
  theforeman.foreman.host_info:
    username: "{{ satellite_deployment_admin_username }}"
    password: "{{ satellite_deployment_admin_password }}"
    server_url: "{{ satellite_deployment_server }}"
    organization: "{{ satellite_deployment_organization }}"
    name: "{{ inventory_hostname }}"
    validate_certs: false
  register: sat_host_reg_final
  failed_when: false
  changed_when: false
  delegate_to: localhost
  when: server_unregister | bool

- name: Remove katello package
  ansible.builtin.dnf: 
    name: katello*
    state: absent
  when: server_unregister | bool

- name: "Assert that the host is absent from Satellite"
  ansible.builtin.assert:
    that:
      - sat_host_reg_final.host is none
    fail_msg: "Host '{{ inventory_hostname }}' is still present in Satellite!"
    success_msg: "Host '{{ inventory_hostname }}' successfully removed from Satellite."
  when: server_unregister | bool
