---
- name: AWS Tag Management
  block:
    - name: Import role aws_role_assume
      ansible.builtin.include_role:
        name: aws_role_assume

    - name: Verify assumed_role is defined and contains required keys
      ansible.builtin.assert:
        that:
          - assumed_role is defined
          - assumed_role.sts_creds is defined
          - assumed_role.sts_creds.access_key is defined
          - assumed_role.sts_creds.secret_key is defined
          - assumed_role.sts_creds.session_token is defined
        fail_msg: >
          The `assumed_role` variable is not defined or does not contain the required keys.
          Ensure the `aws_role_assume` role is executed successfully.
    
    - name: Import role aws_instance_info
      ansible.builtin.include_role:
        name: aws_instance_info

    - name: Verify assumed_role is defined and contains required keys
      ansible.builtin.assert:
        that:
          - metadata_values is defined
        fail_msg: >
          The `metadata_values` variable is not defined or does not contain the required keys.
          Ensure the `aws_instance_info` role is executed successfully.
    
    - name: Set Instance ID as Fact
      ansible.builtin.set_fact:
        instance_id: "{{ metadata_values['instance-id'] }}"
    
    - name: Include aws_tag_create tasks 
      ansible.builtin.include_tasks: aws_tag_create.yml
      when: aws_tag_create | default(false) | bool

    - name: Include aws_tag_delete tasks 
      ansible.builtin.include_tasks: aws_tag_delete.yml
      when: aws_tag_delete | default(false) | bool

    - name: Include aws_tag_delete tasks 
      ansible.builtin.include_tasks: aws_tag_cleanup.yml
      when: aws_tag_cleanup | default(false) | bool

  rescue:
    - name: Handle errors in the block
      ansible.builtin.fail:
        msg: "An error occurred during AWS role assumption or tag management. Details: {{ ansible_failed_result.msg }}"
  
  always:
    - name: Cleanup or final tasks (if needed)
      ansible.builtin.debug:
        msg: "Block execution completed. Proceeding with cleanup or final tasks."
